// GENERATED from porto_features/errors.json — do not edit.
// Run: make sync-error-bindings

export enum PortoErrorCode {
    PORTO_AUTH_FAILED = "PORTO_AUTH_FAILED",
    PORTO_AUTH_DENIED = "PORTO_AUTH_DENIED",
    PORTO_LINKAGE_PENDING = "PORTO_LINKAGE_PENDING",
    PORTO_WALLET_INSUFFICIENT = "PORTO_WALLET_INSUFFICIENT",
    PORTO_TOO_HEAVY = "PORTO_TOO_HEAVY",
    PORTO_DESTINATION_INVALID = "PORTO_DESTINATION_INVALID",
    PORTO_PRODUCT_NOT_FOUND = "PORTO_PRODUCT_NOT_FOUND",
    PORTO_PRODUCT_AMBIGUOUS = "PORTO_PRODUCT_AMBIGUOUS",
    PORTO_PRICE_NOT_FOUND = "PORTO_PRICE_NOT_FOUND",
    PORTO_MARK_FAILED = "PORTO_MARK_FAILED",
    PORTO_MARK_INVALID = "PORTO_MARK_INVALID",
    PORTO_ADDRESS_SENDER_REQUIRED = "PORTO_ADDRESS_SENDER_REQUIRED",
    PORTO_ADDRESS_SENDER_INVALID = "PORTO_ADDRESS_SENDER_INVALID",
    PORTO_ADDRESS_RECIPIENT_REQUIRED = "PORTO_ADDRESS_RECIPIENT_REQUIRED",
    PORTO_ADDRESS_RECIPIENT_INVALID = "PORTO_ADDRESS_RECIPIENT_INVALID",
    PORTO_NETWORK_TIMEOUT = "PORTO_NETWORK_TIMEOUT",
    PORTO_NETWORK_RATE_LIMITED = "PORTO_NETWORK_RATE_LIMITED",
    PORTO_NETWORK_UNAVAILABLE = "PORTO_NETWORK_UNAVAILABLE",
    PORTO_DATA_NOT_FOUND = "PORTO_DATA_NOT_FOUND",
    PORTO_DATA_INVALID = "PORTO_DATA_INVALID",
    PORTO_DATA_CORRUPTED = "PORTO_DATA_CORRUPTED",
    PORTO_DATA_TOO_OLD = "PORTO_DATA_TOO_OLD",
    PORTO_DATA_TOO_NEW = "PORTO_DATA_TOO_NEW",
    PORTO_CAPABILITY_UNSUPPORTED = "PORTO_CAPABILITY_UNSUPPORTED",
    PORTO_TRACKING_UNSUPPORTED = "PORTO_TRACKING_UNSUPPORTED",
    PORTO_TRACKING_NOT_FOUND = "PORTO_TRACKING_NOT_FOUND",
    PORTO_PROVIDER_NOT_CONFIGURED = "PORTO_PROVIDER_NOT_CONFIGURED",
    PORTO_SERVICE_AMBIGUOUS = "PORTO_SERVICE_AMBIGUOUS",
    PORTO_SERVICE_UNSUPPORTED = "PORTO_SERVICE_UNSUPPORTED",
    PORTO_SERVICES_INCOMPATIBLE = "PORTO_SERVICES_INCOMPATIBLE",
}

export const PORTO_ERROR_CODES = Object.values(PortoErrorCode);
